### ISSUE TITLE
Build throws FileNotFoundError validate_core_dirs in Meson

### ISSUE THREAD

**Issue by mlalkaka** [bilelmoussaoui/flatpak-vscode#159]
It seems like a regression was introduced in version 0.0.17 (and still exists in 0.0.25) that causes the build to fail consistently for me. The project uses the Meson build system, and flatpak-vscode was able to build it just fine in 0.0.16. I've pasted the output of the build commands from 0.0.16 (where it succeeded), 0.0.17 (the first version it started failing on), and version 0.0.25. Please let me know if any more information would help.

# Output of init and build on 0.0.16
This build succeeds and running the Run command then appears and works.
```
> flatpak build-init /home/mlalkaka/dev/missive/.flatpak/repo software.mlalkaka.missive org.gnome.Sdk org.gnome.Platform 3.38 <
> flatpak-builder --ccache --force-clean --disable-updates --download-only --state-dir=/home/mlalkaka/dev/missive/.flatpak/flatpak-builder --stop-at=missive /home/mlalkaka/dev/missive/.flatpak/repo /home/mlalkaka/dev/missive/software.mlalkaka.missive.json <
Emptying app dir '/home/mlalkaka/dev/missive/.flatpak/repo'
Downloading sources
Stopping at module missive
> flatpak-builder --ccache --force-clean --disable-updates --disable-download --build-only --keep-build-dirs --state-dir=/home/mlalkaka/dev/missive/.flatpak/flatpak-builder --stop-at=missive /home/mlalkaka/dev/missive/.flatpak/repo /home/mlalkaka/dev/missive/software.mlalkaka.missive.json <
Initializing build dir
Committing stage init to cache
Starting build of software.mlalkaka.missive
Stopping at module missive
Pruning cache
> flatpak build --share=network --nofilesystem=host --filesystem=/home/mlalkaka/dev/missive --filesystem=/home/mlalkaka/dev/missive/.flatpak/repo --env=PATH=/home/mlalkaka/dev/missive/.venv/bin:/home/mlalkaka/.cargo/bin:/home/mlalkaka/.local/bin:/home/mlalkaka/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --filesystem=/home/mlalkaka/dev/missive/_build /home/mlalkaka/dev/missive/.flatpak/repo meson --prefix /app _build  <
Using 'PKG_CONFIG_PATH' from environment with value: '/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig'
Using 'PKG_CONFIG_PATH' from environment with value: '/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig'
The Meson build system
Version: 0.56.2
Source dir: /home/mlalkaka/dev/missive
Build dir: /home/mlalkaka/dev/missive/_build
Build type: native build
Project name: missive
Project version: 0.1.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program desktop-file-validate found: YES (/usr/sbin/desktop-file-validate)
Program appstream-util found: YES (/usr/sbin/appstream-util)
Program glib-compile-schemas found: YES (/usr/sbin/glib-compile-schemas)
Found pkg-config: /usr/sbin/pkg-config (1.8.0)
Using 'PKG_CONFIG_PATH' from environment with value: '/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig'
Program glib-compile-resources found: YES (/usr/sbin/glib-compile-resources)
Program python3 found: YES (/home/mlalkaka/dev/missive/.venv/bin/python3)
Configuring missive using configuration
Program build-aux/meson/postinstall.py found: YES (/home/mlalkaka/dev/missive/build-aux/meson/postinstall.py)
Build targets in project: 6

Found ninja-1.10.2 at /usr/sbin/ninja
> flatpak build --share=network --nofilesystem=host --filesystem=/home/mlalkaka/dev/missive --filesystem=/home/mlalkaka/dev/missive/.flatpak/repo --env=PATH=/home/mlalkaka/dev/missive/.venv/bin:/home/mlalkaka/.cargo/bin:/home/mlalkaka/.local/bin:/home/mlalkaka/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --filesystem=/home/mlalkaka/dev/missive/_build /home/mlalkaka/dev/missive/.flatpak/repo ninja -C _build <
ninja: Entering directory `_build'
[1/3] Generating missive_gresource with a custom command
[2/3] Generating software.mlalkaka.missive.desktop_data_merge with a custom command
[3/3] Generating software.mlalkaka.missive.appdata.xml_data_merge with a custom command
> flatpak build --share=network --nofilesystem=host --filesystem=/home/mlalkaka/dev/missive --filesystem=/home/mlalkaka/dev/missive/.flatpak/repo --env=PATH=/home/mlalkaka/dev/missive/.venv/bin:/home/mlalkaka/.cargo/bin:/home/mlalkaka/.local/bin:/home/mlalkaka/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --filesystem=/home/mlalkaka/dev/missive/_build /home/mlalkaka/dev/missive/.flatpak/repo meson install -C _build <
ninja: Entering directory `_build'
ninja: no work to do.
gtk-update-icon-cache: Failed to open file /app/share/icons/hicolor/.icon-theme.cache : No such file or directory
Updating icon cache...
Updating desktop database...
Compiling GSettings schemas...
Installing data/software.mlalkaka.missive.desktop to /app/share/applications
Installing data/software.mlalkaka.missive.appdata.xml to /app/share/appdata
Installing src/missive.gresource to /app/share/missive
Installing /home/mlalkaka/dev/missive/data/software.mlalkaka.missive.gschema.xml to /app/share/glib-2.0/schemas
Installing /home/mlalkaka/dev/missive/_build/src/missive to /app/bin
Installing /home/mlalkaka/dev/missive/src/__init__.py to /app/share/missive/missive
Installing /home/mlalkaka/dev/missive/src/main.py to /app/share/missive/missive
Installing /home/mlalkaka/dev/missive/src/main_window.py to /app/share/missive/missive
Installing /home/mlalkaka/dev/missive/src/window.py to /app/share/missive/missive
Running custom install script '/usr/bin/meson --internal gettext install --subdir=po --localedir=share/locale --pkgname=missive'
Running custom install script '/home/mlalkaka/dev/missive/build-aux/meson/postinstall.py'
```

# Output of init and build on 0.0.17
This build fails.
```
Downloading sources
Stopping at module missive
>>> flatpak-builder --ccache --force-clean --disable-updates --disable-download --build-only --keep-build-dirs --state-dir=/home/mlalkaka/dev/missive/.flatpak/flatpak-builder --stop-at=missive /home/mlalkaka/dev/missive/.flatpak/repo /home/mlalkaka/dev/missive/software.mlalkaka.missive.json
Initializing build dir
Committing stage init to cache
Starting build of software.mlalkaka.missive
Stopping at module missive
Pruning cache
>>> flatpak build --share=network --nofilesystem=host --filesystem=/home/mlalkaka/dev/missive --filesystem=/home/mlalkaka/dev/missive/.flatpak/repo --env=PATH=/home/mlalkaka/dev/missive/.venv/bin:/home/mlalkaka/.cargo/bin:/home/mlalkaka/.local/bin:/home/mlalkaka/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --filesystem=/home/mlalkaka/dev/missive/_build /home/mlalkaka/dev/missive/.flatpak/repo meson --prefix /app _build 
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mesonbuild/mesonmain.py", line 140, in run
    return options.run_func(options)
  File "/usr/lib/python3.8/site-packages/mesonbuild/msetup.py", line 252, in run
    app = MesonApp(options)
  File "/usr/lib/python3.8/site-packages/mesonbuild/msetup.py", line 63, in __init__
    (self.source_dir, self.build_dir) = self.validate_dirs(options.builddir,
  File "/usr/lib/python3.8/site-packages/mesonbuild/msetup.py", line 135, in validate_dirs
    (src_dir, build_dir) = self.validate_core_dirs(dir1, dir2)
  File "/usr/lib/python3.8/site-packages/mesonbuild/msetup.py", line 124, in validate_core_dirs
    if os.path.samefile(dir1, dir2):
  File "/usr/lib/python3.8/genericpath.py", line 101, in samefile
    s2 = os.stat(f2)
FileNotFoundError: [Errno 2] No such file or directory: ''
>>> Child process exited with code 2
```

# Output of init and build on 0.0.25
To verify this regression still exists, here's the output on the latest version. The error at the end remains the same.
```
>>> flatpak-builder --ccache --force-clean --disable-updates --disable-download --build-only --keep-build-dirs --state-dir=/home/mlalkaka/dev/missive/.flatpak/flatpak-builder --stop-at=missive /home/mlalkaka/dev/missive/.flatpak/repo /home/mlalkaka/dev/missive/software.mlalkaka.missive.json
Initializing build dir
Committing stage init to cache
Starting build of software.mlalkaka.missive
Stopping at module missive
Pruning cache
>>> flatpak build --share=network --nofilesystem=host --filesystem=/home/mlalkaka/dev/missive --filesystem=/home/mlalkaka/dev/missive/.flatpak/repo --env=PATH=/home/mlalkaka/dev/missive/.venv/bin:/home/mlalkaka/.cargo/bin:/home/mlalkaka/.local/bin:/home/mlalkaka/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --filesystem=/home/mlalkaka/dev/missive/_build /home/mlalkaka/dev/missive/.flatpak/repo meson --prefix /app _build 
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mesonbuild/mesonmain.py", line 140, in run
    return options.run_func(options)
  File "/usr/lib/python3.8/site-packages/mesonbuild/msetup.py", line 252, in run
    app = MesonApp(options)
  File "/usr/lib/python3.8/site-packages/mesonbuild/msetup.py", line 63, in __init__
    (self.source_dir, self.build_dir) = self.validate_dirs(options.builddir,
  File "/usr/lib/python3.8/site-packages/mesonbuild/msetup.py", line 135, in validate_dirs
    (src_dir, build_dir) = self.validate_core_dirs(dir1, dir2)
  File "/usr/lib/python3.8/site-packages/mesonbuild/msetup.py", line 124, in validate_core_dirs
    if os.path.samefile(dir1, dir2):
  File "/usr/lib/python3.8/genericpath.py", line 101, in samefile
    s2 = os.stat(f2)
FileNotFoundError: [Errno 2] No such file or directory: ''
>>> Child process exited with code 2
```

**Comment by SeaDve** [comment]
I'll try to debug it. May you show the manifest to reproduce the issue?

**Comment by mlalkaka** [comment]
Thanks! Here's the contents of the manifest file:
```
{
    "app-id" : "software.mlalkaka.missive",
    "runtime" : "org.gnome.Platform",
    "runtime-version" : "3.38",
    "sdk" : "org.gnome.Sdk",
    "command" : "missive",
    "finish-args" : [
        "--share=network",
        "--share=ipc",
        "--socket=fallback-x11",
        "--socket=wayland"
    ],
    "cleanup" : [
        "/include",
        "/lib/pkgconfig",
        "/man",
        "/share/doc",
        "/share/gtk-doc",
        "/share/man",
        "/share/pkgconfig",
        "*.la",
        "*.a"
    ],
    "modules" : [
        {
            "name" : "missive",
            "builddir" : true,
            "buildsystem" : "meson",
            "sources" : [
                {
                    "type" : "git",
                    "url" : "file:///home/mlalkaka/dev/missive"
                }
            ]
        }
    ]
}
```

**Comment by SeaDve** [comment]
Thanks; do you have the repo somewhere?

**Comment by mlalkaka** [comment]
I don't yet, but here's a simplified project that reproduces the issue: [flatpak-vscode-bug.zip](https://github.com/bilelmoussaoui/flatpak-vscode/files/8500843/flatpak-vscode-bug.zip).

**Comment by SeaDve** [comment]
I wasn't able to reproduce it:
```bash
>>> flatpak-builder --ccache --force-clean --disable-updates --disable-download --build-only --keep-build-dirs --state-dir=/home/dave/Downloads/flatpak-vscode-bug/.flatpak/flatpak-builder --stop-at=missive /home/dave/Downloads/flatpak-vscode-bug/.flatpak/repo /home/dave/Downloads/flatpak-vscode-bug/software.mlalkaka.missive.json
Initializing build dir
Committing stage init to cache
Starting build of software.mlalkaka.missive
Stopping at module missive
Pruning cache
>>> flatpak build --share=network --nofilesystem=host --filesystem=/home/dave/Downloads/flatpak-vscode-bug --filesystem=/home/dave/Downloads/flatpak-vscode-bug/.flatpak/repo --env=PATH=/home/dave/Projects/my-scripts:/home/dave/.cargo/bin:/home/dave/Projects/my-scripts:/home/dave/.local/bin:/home/dave/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --filesystem=/home/dave/Downloads/flatpak-vscode-bug/_build /home/dave/Downloads/flatpak-vscode-bug/.flatpak/repo meson --prefix /app _build 
The Meson build system
Version: 0.59.4
Source dir: /home/dave/Downloads/flatpak-vscode-bug
Build dir: /home/dave/Downloads/flatpak-vscode-bug/_build
Build type: native build
Project name: missive
Project version: 0.1.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Program glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Program python3 found: YES (/usr/bin/python3)
Program build-aux/meson/postinstall.py found: YES (/home/dave/Downloads/flatpak-vscode-bug/build-aux/meson/postinstall.py)
Build targets in project: 1

Found ninja-1.10.2 at /usr/bin/ninja
```

**Comment by mlalkaka** [comment]
Ah, it looks like your build was using Meson version 0.59.4, whereas mine was using version 0.56.2 (from Flatpak SDK org.gnome.Sdk version 3.38). If I update the runtime-version in the manifest to "42", then Meson version 0.59.4 gets used, and I get past the error I was facing. Does using version "3.38" of the Sdk allow you to reproduce the error?

**Comment by bilelmoussaoui** [comment]
That seems like a meson error and 3.38 is way too old

**Comment by mlalkaka** [comment]
Yeah I wasn't sure, though, because when I ran that same `flatpak build` command from the terminal instead of from flatpak-vscode, it worked fine with version 3.38 of the SDK. So it seemed like the cause was the extension. I can upgrade the SDK version, so feel free to close if it's not worth pursuing further. Thanks for your help!

**Comment by bilelmoussaoui** [comment]
I will go ahead and close this one, if you notice any related issues please feel free to re-open it.
