### ISSUE TITLE
GLIBC_2.34' not found error when opening a flatpak rust project

### ISSUE THREAD

**Issue by SeaDve** [bilelmoussaoui/flatpak-vscode#46]
VS Code version: 1.63.2 (from flatpak)
Flatpak vscode extension version: 0.0.16
Rust analyzer extension version: 0.2.853
Application Runtime: GNOME 42

Steps to reproduce:
1. Open rust flatpak project with this and rust-analyzer extension

Rust Analyzer Client Output:
```shell
INFO [2/4/2022, 8:55:33 PM]: Using server binary at /home/dave/Projects/noteworthy/.flatpak/rust-analyzer.sh
DEBUG [2/4/2022, 8:55:33 PM]: Checking availability of a binary at /home/dave/Projects/noteworthy/.flatpak/rust-analyzer.sh
DEBUG [2/4/2022, 8:55:33 PM]: /home/dave/Projects/noteworthy/.flatpak/rust-analyzer.sh --version: {
  status: 1,
  signal: null,
  output: [
    null,
    '',
    "rust-analyzer: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by rust-analyzer)\n"
  ],
  pid: 522,
  stdout: '',
  stderr: "rust-analyzer: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by rust-analyzer)\n"
}
ERROR [2/4/2022, 8:55:33 PM]: Bootstrap error [Error: Failed to execute /home/dave/Projects/noteworthy/.flatpak/rust-analyzer.sh --version. `config.server.path` or `config.serverPath` has been set explicitly.            Consider removing this config or making a valid server binary available at that path.
	at L0 (/home/dave/.var/app/com.visualstudio.code/data/vscode/extensions/matklad.rust-analyzer-0.2.853/out/main.js:109:3705)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async F0 (/home/dave/.var/app/com.visualstudio.code/data/vscode/extensions/matklad.rust-analyzer-0.2.853/out/main.js:109:1881)
	at async O0 (/home/dave/.var/app/com.visualstudio.code/data/vscode/extensions/matklad.rust-analyzer-0.2.853/out/main.js:108:3977)
	at async lC (/home/dave/.var/app/com.visualstudio.code/data/vscode/extensions/matklad.rust-analyzer-0.2.853/out/main.js:108:3808)
	at async Promise.all (index 0)]

```

**Comment by bilelmoussaoui** [comment]
Have you tried removing also the `.flatpak` folder, close vscode and re-open it and start a new build from scratch?

**Comment by SeaDve** [comment]
> Have you tried removing also the .flatpak folder, close vscode and re-open it and start a new build from scratch?

Yeah, I tried it again recently with all files closed

**Comment by bilelmoussaoui** [comment]
Is this a flatpaked vscode ? If so, can you open a build terminal and run r-a there and see how that goes ?

**Comment by SeaDve** [comment]
It outputs the same error `rust-analyzer: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by rust-analyzer)`. It seems to be not an issue to the extension?

**Comment by SeaDve** [comment]
After removing the path to ~/.cargo/bin/cargo in `$PATH`, it somehow works properly now.

Closing this I guess, thanks!

**Comment by bilelmoussaoui** [comment]
That is weird, we should probably hardcode the path to make sure we use the SDK rust analyzer

**Comment by SeaDve** [comment]
ill make an issue about that
